CREATE TABLE CUSTOMER (
    CUSTOMER_ID int,
    FIRST_NAME_CUSTOMER varchar(255),
    LAST_NAME_CUSTOMER varchar(255),
	DOCUMENT_CUSTOMER varchar(255),
	ADDRESS_CUSTOMER varchar(255),
    PHONE_CUSTOMER varchar(255),
	DISTRICT_CUSTOMER varchar(255),
	CITY_CUSTOMER varchar(255)
	);

	
	CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID int,
    FIRST_NAME_EMPLOYEE varchar(255),
    LAST_NAME_EMPLOYEE varchar(255),
	DOCUMENT_EMPLOYEE varchar(255),
	PHONE_EMPLOYEE varchar(255)
	);
	
		CREATE TABLE PRODUCT (
    PRODUCT_ID int,
	NAME_PRODUCT varchar(255),
    TYPE_PRODUCT varchar(255),
	VALUE_PRODUCT varchar(255),
	SHOP_PRODUCT varchar(255)
	);
	
	CREATE TABLE SALLER (
    SALLER_ID int,
    FIRST_NAME_SALLER varchar(255), 
    LAST_NAME_SALLER varchar(255),
	EMAIL_SALLER varchar(255),
	DOCUMENT_SALLER varchar (255),
	PHONE_SALLER varchar(255)
	);